app:
  name: "web_app"
  mode: "dev"
  port: 8082
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "lxy13607073088"
  dbname: "hackathon"
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  password: ""
#log:
#  level: "debug"
#  filename: "web_qpp.log"
#  max_size: 200
#  max_age: 30
#  max_backups: 7